name: mustachehub
description: A logic-less text template generator powered by mustache templates.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependency_overrides: 
  mustachex: 
    path: cloned_apis/mustachex
 

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  # firebase_auth: ^4.10.1
  # firebase_core: ^2.17.0
  # cloud_firestore: ^4.9.3
  # firebase_storage: ^11.2.8
  cupertino_icons: ^1.0.2
  easy_isolate_mixin: ^1.0.1
  animated_flip_counter: ^0.2.6
  flutter_modular: ^6.3.2
  hydrated_bloc: ^9.1.3
  flutter_animate: ^4.3.0
  dotted_border: ^2.1.0 
  cursor_autocomplete_options: ^1.3.1
  faker: ^2.1.0
  uuid:
  result_dart: ^1.1.0
  hive: ^2.2.3
  flutter_credit_card: ^4.0.1
  image_network: ^2.5.4+1
  flutter_web_plugins: 
    sdk: flutter

  mustachex:
  mason: 
    path: cloned_apis/mason
  
  # State manegment and Dependency injection
  flutter_hooks: ^0.20.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2 
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.1
  equatable: ^2.0.5
  lottie: ^2.7.0
  image_picker: ^1.0.5
  image_picker_for_web: ^3.0.1
  url_launcher: ^6.2.2 
  sandbox_logger: ^2.0.1
  flutter_fancy_tree_view: ^1.4.1
  awesome_snackbar_content: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3 
  freezed: ^2.3.2
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
