name: mustachehub
description: A logic-less text template generator powered by mustache templates.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependency_overrides: 
  mustache_template: 
    path: packages/mustache
 

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.7
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  hydrated_bloc: ^9.1.2
  flutter_animate: ^4.2.0+1
  dotted_border: 2.0.0+3
  uuid:
  result_dart:
  hive: ^2.2.3
  flutter_credit_card: 3.0.7 
  image_network: ^2.5.4+1
  flutter_web_plugins: 
    sdk: flutter
  mustache_template: 
  mason: 
    path: packages/mason
  
  # State manegment and Dependency injection
  flutter_hooks: ^0.20.0 
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2 
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.15 
  equatable: ^2.0.5
  lottie: ^2.6.0
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  url_launcher: ^6.1.14
  sandbox_logger: ^2.0.1
  awesome_snackbar_content: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3 
  freezed: ^2.3.2
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
