name: mustachehub
description: A logic-less text template generator powered by mustache templates.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' 
dependency_overrides: 
  mustache_template: 
    path: packages/mustache

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.0 
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  freezed_annotation: ^2.2.0
  mustache_template: 
  mason: 
    path: packages/mason/packages/mason
  equatable:
  flutter_modular: ^6.1.1
  flutter_animate: ^4.2.0+1
  dotted_border: 2.0.0+3
  path_provider: ^2.0.15
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  dartz: ^0.10.1
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.5
  url_launcher: ^6.1.12
  sandbox_logger:
  # flutter_reorderable_list: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3 
  freezed: ^2.3.2
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true