// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGm0B5dZ3w5a3JrVO37xBIHoqoOVG58WM',
    appId: '1:137409650490:web:637ad3fb1f10a882f1ba03',
    messagingSenderId: '137409650490',
    projectId: 'mustachehub',
    authDomain: 'mustachehub.firebaseapp.com',
    storageBucket: 'mustachehub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkCo0rKuKUv2Bvr6-Q68VBRXNkdNG450',
    appId: '1:137409650490:android:3a6288997b0bc9c2f1ba03',
    messagingSenderId: '137409650490',
    projectId: 'mustachehub',
    storageBucket: 'mustachehub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEDrig4NXI7Vvo_kWA-BdWf0OumQXJSfc',
    appId: '1:137409650490:ios:c8d6cd596ad8c315f1ba03',
    messagingSenderId: '137409650490',
    projectId: 'mustachehub',
    storageBucket: 'mustachehub.appspot.com',
    iosClientId: '137409650490-u03jc5vistgk8em7p8rp1vars4ihdev3.apps.googleusercontent.com',
    iosBundleId: 'com.mustachehub.mustachehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEDrig4NXI7Vvo_kWA-BdWf0OumQXJSfc',
    appId: '1:137409650490:ios:144d4e5682cfcea7f1ba03',
    messagingSenderId: '137409650490',
    projectId: 'mustachehub',
    storageBucket: 'mustachehub.appspot.com',
    iosClientId: '137409650490-nhtivfijinrgp10iar2ecuc3l4jpra7b.apps.googleusercontent.com',
    iosBundleId: 'com.mustachehub.mustachehub.RunnerTests',
  );
}
