name: collection_conductor
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

isar_version: &isar_version 3.1.0

dependencies: 
  isar: *isar_version
  isar_flutter_libs: *isar_version
  equatable: any
  uuid: any
  result_dart: any
  dson_adapter: any
  path_provider: any 
  cloud_firestore: any
  fire: any
  firebase_core: any
  internet_connection_checker_plus: ^2.0.0
  connectivity_plus: ^4.0.2
  flutter_bloc: any
  bloc: any
  freezed_annotation: any
  flutter_modular: ^6.1.1

dev_dependencies:
  lints: ^2.0.0
  flutter_lints: any
  test: ^1.21.0
  isar_generator: *isar_version
  build_runner: any
  freezed: ^2.3.2
  json_serializable: ^6.7.0